
project_id = "qdxpxqdewqrbvlsajeeo"
[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[auth]
port = 54324

[inbucket]
port = 54325

[storage]
port = 54326

[realtime]
port = 54327

[functions]
port = 54328

[functions.slave-webhook]
verify_jwt = false
