
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdxpxqdewqrbvlsajeeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkeHB4cWRld3FyYnZsc2FqZWVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2NzM0MDMsImV4cCI6MjA1MzI0OTQwM30.-wnDf1hMWOow3O1kbcTfC3mw59h-5SsmdFGhp5bKgUE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Utility function to get proxy URL by ID
export const getProxyUrlById = async (proxyId: string): Promise<string | null> => {
  if (!proxyId) return null;
  
  const { data, error } = await supabase
    .from('proxies')
    .select('address, port, username, password')
    .eq('id', proxyId)
    .single();
    
  if (error || !data) {
    console.error('Error fetching proxy:', error);
    return null;
  }
  
  // Format: address:port:username:password or address:port
  if (data.username && data.password) {
    return `${data.address}:${data.port}:${data.username}:${data.password}`;
  }
  
  return `${data.address}:${data.port}`;
};

// Get random valid proxy
export const getRandomValidProxy = async (): Promise<string | null> => {
  const { data, error } = await supabase
    .from('proxies')
    .select('id, address, port, username, password')
    .eq('valid', true)
    .limit(50);
    
  if (error || !data || data.length === 0) {
    console.error('Error fetching valid proxies:', error);
    return null;
  }
  
  // Select a random proxy from the result
  const randomIndex = Math.floor(Math.random() * data.length);
  const proxy = data[randomIndex];
  
  // Format: address:port:username:password or address:port
  if (proxy.username && proxy.password) {
    return `${proxy.address}:${proxy.port}:${proxy.username}:${proxy.password}`;
  }
  
  return `${proxy.address}:${proxy.port}`;
};

// Fetch screenshot for a viewer
export const getViewerScreenshot = async (viewerId: string): Promise<string | null> => {
  // First check if the column exists by doing a metadata query
  const { data: metaData, error: metaError } = await supabase
    .from('viewers')
    .select('error') // Select any valid column just to check if the table exists
    .eq('id', viewerId)
    .limit(1);
    
  if (metaError) {
    console.error('Error accessing viewers table:', metaError);
    return null;
  }
  
  // Now try to get the screenshot, but handle the case where the column doesn't exist
  try {
    // Instead of using RPC which seems to have type issues, let's directly query the database
    const { data, error } = await supabase
      .from('viewers')
      .select('*')
      .eq('id', viewerId)
      .single();
    
    if (error) {
      console.error('Error fetching viewer data:', error);
      return null;
    }
    
    // Check if the data has a screenshot property
    if (data && 'screenshot' in data) {
      return data.screenshot as string;
    } else {
      console.log('Viewer found but screenshot is not available');
      return null;
    }
  } catch (error) {
    console.error('Screenshot functionality not available:', error);
    return null;
  }
};

// Send command to slaves
export const sendCommand = async (command: {
  type: 'spawn' | 'stop' | 'update_proxy' | 'reconnect' | 'custom';
  target: string;
  payload: Record<string, any>;
}): Promise<string | null> => {
  const { type, target, payload } = command;
  
  const { data, error } = await supabase
    .from('commands')
    .insert([{
      type,
      target,
      payload,
      timestamp: new Date().toISOString(),
      status: 'pending'
    }])
    .select()
    .single();
    
  if (error) {
    console.error('Error sending command:', error);
    return null;
  }
  
  return data.id;
};
